### ISSUE TITLE
Bug: Recurrence of no data for ZNO in lambda log with lambda not terminating

### ISSUE THREAD

**Issue by sluofoss** [sluofoss/stock-stream#12]
# Desc: 
when trigger multiple lambda from event bridge, (1 per minute on cron * * * * * *) the lambda log receives new event long outside bound of 15min, this is odd and even though the billed time was capped (appears to be) at 9000s, this does eat into the concurrency count.

# TODO:
- figure out why this is happening
- [x] check if this happens when triggering the lambda manual from lambda console with test.
    - result: 
        - at least no more new log after timeout time is reached, 
        - also runs into this issue        
        - it seems like `Saving to local` and `Symbol request is successful with len` only have 1 occur during test for `14D.AX`
- [x] check what happens when we remove most symbol from csv b4 executing
- [x] check what happens when run locally

# investigation result:
this has to do with lambda role policy permissions, adding the managed policy s3full access works. seems to be related to the definition of service: s3-object-lambda

**Comment by lu0x1a0** [comment]
lets start again with something so simple, so no multi threading nothing. just 1 process 1 thread 1 symbol and to s3, see if that works.
